apiVersion: v1
kind: Pod
metadata:
  name: eip-controller
  #namespace: kube-system
  labels:
    k8s-app: eip-controller
    version: v1
spec:
  hostNetwork: true
  containers:
  - name: eip-controller
    image: kope/eip-controller
    command:
    - /usr/bin/eip-controller
    - --eip=52.20.89.150
    - --eip=52.205.217.35
    - --v=4
